017 - Storage Buckets
appwrite/rfc pull request #25
Opened 2021-05-26 15:00 UTC by TorstenDittmann

https://github.com/appwrite/rfc/blob/feat-storage-buckets/017-storage-buckets.md

2021-05-30 06:39 UTC, lohanidamodar commented on 017-storage-buckets.md
> +  - This setting decides if files are scanned by ClamAV after upload. Same reasoning ass **Encryption**.
```suggestion
  - This setting decides if files are scanned by ClamAV after upload. Same reasoning as **Encryption**.
```

2021-05-30 06:39 UTC, lohanidamodar commented on 017-storage-buckets.md
> +Let's take a look at the `GET: /v1/storage/files/{fileId}` endpoint. This will result into retrieving a file from the current Storage service. Now if a file is inside a Bucket - the endpoint would ha
1. I like the endpoint `/v1/storage/files/{bucketId}/{fileId}
2. If no bucket is created may be appwrite can handle the bucket as `default` internally
3. Internally any path passed only as `/v1/storage/files/{fileId}` appwrite internally converts to `/v1/storage/files/default/{fileId}`

2021-05-30 06:42 UTC, lohanidamodar commented
May be not real time but I'would also love to have and be able to get the usage via API
1. Be able to get `total space used`
2. Be able to get `total bandwidth transferred (upload and download)

This is useful if,
for example I create separate bucket for each of my users and limit their max bandwidth and max storage.

2021-05-30 15:27 UTC, eldadfux commented on 017-storage-buckets.md
> +- **TTL**
We should make sure we calculate storage usage properly when TTL expires

2021-05-30 15:27 UTC, eldadfux commented on 017-storage-buckets.md
> +- **TTL**
Should we also allow TTL per file?

2021-05-30 15:27 UTC, eldadfux commented on 017-storage-buckets.md
> +#### `GET: /v1/storage/bucket/`
In order to be persistent with our current conventions this should be `/v1/storage/buckets/`

2021-05-30 15:27 UTC, eldadfux commented on 017-storage-buckets.md
> +#### `POST: /v1/storage/bucket`
To simplify the API, and avoid passing complex object I think we should seriously consider have an individual POST endpoint for each adapter. Each endpoint will be able to receive primitive params that the adapter needs. Internally we can store the data as an object. A unique index for a unique adapter will make the documentation and API easier to understand and will be more consistent with current behavior that favorite the usage of plain primitive params.

For example:
``POST: /v1/storage/bucket/s3`
basic params for bucket creation + 
string - accessKey
string- secretKey
string - bucketName
string - region
string - aclFlag

2021-05-30 15:27 UTC, eldadfux commented on 017-storage-buckets.md
> +- **maximumFiles = null** Maximum amount of files.
What happens when we are over capacity after update?

2021-05-30 15:27 UTC, eldadfux commented on 017-storage-buckets.md
> +This endpoint deletes a Bucket by its unique ID. *Server*
This endpoint should trigger a background delete of all files in the bucket from both db and storage. This action should probably be delayed by x time to avoid abuse or actions by unauthorized users. The delay will give a time window to revert the action on the server admin level.

2021-05-30 15:27 UTC, eldadfux commented on 017-storage-buckets.md
> +This endpoint deletes a Bucket by its unique ID. *Server*
We might want to do something similar on a collection delete

2021-05-30 15:27 UTC, eldadfux commented on 017-storage-buckets.md
> +- Having 2 separate endpoints for each, the default Storage and Storage Buckets, with its own SDK methods
`Having 2 separate endpoints for each, the default Storage and Storage Buckets, with its own SDK methods`

I think this is the best and simplest option for us. We can change the names of old endpoints in the new SDK to have a prefix we decide.

2021-05-31 11:21 UTC, TorstenDittmann commented on 017-storage-buckets.md
> +- **maximumFiles = null** Maximum amount of files.
Same with the user limits - we won't allow any more uploads.

2021-05-31 14:05 UTC, TorstenDittmann commented on 017-storage-buckets.md
> +- **TTL**
Added 👍🏻

2021-05-31 14:06 UTC, TorstenDittmann commented on 017-storage-buckets.md
> +#### `POST: /v1/storage/bucket`
Added.

2021-05-31 14:06 UTC, TorstenDittmann commented on 017-storage-buckets.md
> +This endpoint deletes a Bucket by its unique ID. *Server*
Added.

2021-06-08 11:15 UTC, eldadfux requested changes

2021-06-08 11:15 UTC, eldadfux commented on 017-storage-buckets.md
> +This endpoint deletes a Bucket by its unique ID. *Server*
We should also add and emphasis the **delayed** part, if a malicious user is triggering a full bucket delete we want to have a timeframe where we can still stop the operation.

2021-06-08 11:15 UTC, eldadfux commented on 017-storage-buckets.md
> +Let's take a look at the `GET: /v1/storage/files/{fileId}` endpoint. This will result into retrieving a file from the current Storage service. Now if a file is inside a Bucket - the endpoint would ha
We will do something like that **temporarily** for backward compatibility, but this will not be consisted with the way we handle all other endpoint paths across Appwrite ([service]/[entity]/[id]).

2021-06-08 11:15 UTC, eldadfux commented on 017-storage-buckets.md
> +- **adapterAcl** S3 Access Control List.
```suggestion
- **accessKeyId** S3 Access Key ID.
- **secretKey** S3 Secret Key.
- **bucket** S3 Bucket Name.
- **region** S3 Region.
- **acl** S3 Access Control List.
```

The adapter context is already clear from the path/title

2021-06-08 11:15 UTC, eldadfux commented on 017-storage-buckets.md
> +- **allowedFileExtensions = null** Allowed File extensions.
```suggestion
- **name** Bucket name.
- **write** An array of strings with write permissions.
- **encrypted = true** Enable Encryption.
- **antivirus = true** Enable Anti Virus.
- **ttl = false** Enables TTL for files.
- **maxFiles = null** Maximum amount of files.
- **maxFileSize = null** Maximum file size.
- **fileExtensions = null** Allowed File extensions. Leave empty to allow any extension.
```

Added a few suggestions to param names - still not 100% sure about them.

I think we should consider to implement bot `maxFiles` and `ttl` options in a later stage, not sure how well the DB will scale with them.

2021-06-14 11:54 UTC, eldadfux approved these changes

2021-06-17 09:59 UTC, merged